tasks:
  - type: docker-build
    image: elysium
    auto:
      - source: push
        has_tag: true
        tag_source: tag
      - source: push
        has_tag: true
        tag_source: latest
    context: Elysium
    file: Elysium/Elysium/Dockerfile
    registries:
      - gitlab
  - type: docker-build
    image: elysium-silo
    auto:
      - source: push
        has_tag: true
        tag_source: tag
      - source: push
        has_tag: true
        tag_source: latest
    context: Elysium
    file: Elysium/Elysium.Silo.Api/Dockerfile
    registries:
      - gitlab